### ISSUE TITLE
[Question] Is luajit-remake a drop-in replacement to LuaJIT

### ISSUE THREAD

**Issue by AlexanderMisel** [luajit-remake/luajit-remake#1]
We know that LuaJIT has many uses, including OpenResty, and I wonder if the goal of LuaJIT-remake is to be able to serve as an alternative to LuaJIT. Does it support the convenient FFI interface that LuaJIT provides?

It seems LuaJIT-remake doesn't provide an interactive REPL. When I first run `luajitr`, it outputs:
```
LuaJIT Remake v0.0.1 (f8fb972, release build)
Copyright (C) 2022 Haoran Xu. https://luajit-remake.github.io

usage: luajitr <script> [args]...
```

**Comment by sillycross** [comment]
This is a research project, and it is written from scratch, because I don't have any experience with the PUC Lua or LuaJIT codebase, and I need maximal flexibility for the purpose of research. This is why every non-essential feature is missing.

I intend to eventually make this project production-ready. However, it will be a _very_ long way to go: I do not anticipate this can happen in 1 or 2 years. And for obvious reasons, support for extension features won't happen until the VM is production ready, so it's just too early to consider all sorts of "will LJR support xyz" questions.

**Comment by sillycross** [comment]
The performance of dynamic languages is a very complex topic. It's not as easy as running some synthetic tests, so I recommend you to not look at these numbers too seriously. 

And LuaJIT is definitely _not_ unbeatable: for synthetic long-running workloads, I see no reason that how LuaJIT's tracing compiler can rival, say, JSC's FTL tier, especially on real-world workloads where unpredictable branches are common. LuaJIT's GC is also toy compared with JSC, and LuaJIT doesn't have hidden class (the HREFK thing in LuaJIT's JIT tier will never rival a true hidden class implementation, especially when metatables are involved).  

So at the end, it's still the problem of how much engineering resource you have. JavaScript is fortunate to have a drastic amount of engineering resource poured into it so it can have the best JIT possible, despite all the JS nonsense semantics.
