### ISSUE TITLE
Functions not implemented yet and temporary solutions

### ISSUE THREAD

**Issue by CapsAdmin** [luajit-remake/luajit-remake#10]
I know you probably want to spend time on other important things, but I was interested in testing this version of Lua to see how it currently performs and or crashes. However since many library functions are lacking it's a bit hard to explore.

As a temporary solution I hacked together this compat library thing
https://gist.github.com/CapsAdmin/d736f244e38d68f2ccc792d3e5d576ca
Where you'd do `loadfile("luajit_remake_compat.lua")()` to get string, bit, require and table library implemented in pure lua

I want to try and run the test suite on my project https://github.com/CapsAdmin/NattLua but currently blocking for me are `io.open`, `io.popen` and `os.execute` I think.

**Comment by sillycross** [comment]
Thanks for the work, and thanks for reporting.

`os.execute` should be very easy to implement, maybe the easiest thing to do is to copy and adapt code from `string.upper`.

`io.open` and `io.popen` are harder, mainly because we don't have proper support for USERDATA and GC yet. Supporting C API (thus USERDATA) is a lot of design work, and as you can guess I need to prioritize on the optimizing JIT tier first. And supporting GC is even more work (Lua relies on GC finalizer to close file descriptors). 

If you only want to test, it's not hard to write a makeshift implementation: for example, you can just return the file descriptor number you get from `open` and make the reader functions expect numbers instead of USERDATA objects. 

However, LJR aims at compatibility with official Lua 5.1, so I'd rather leave things as unimplemented than using makeshift implementations that isn't fully compatible with Lua 5.1: it's much easier to diagnose an "unimplemented" error message than debugging weird bugs caused by subtle behavior difference. 

The same applies to your workaround script: while I appreciate your work, I can't merge it into the official repo for the same reason: I'd rather people getting an "unimplemented" error than getting weird bugs or poor performance due to the compat library (which will make them immediately lose confidence on this project).
