### ISSUE TITLE
Building without docker

### ISSUE THREAD

**Issue by Frityet** [luajit-remake/luajit-remake#13]
Hello, I would like to build this project without docker, so just on my host system because I am using MacOS and would like to test and help develop it outside of a container. Is this supported? Or should I make a PR to add this?

P.S:
Thank you so mcuh for this project, I am so excited to see where this goes

**Comment by sillycross** [comment]
> because I am using MacOS

If you are using M1 or later, this project won't work on your system right now since it currently only supports x86-64. 

> I would like to test and help develop it outside of a container

The container is only to provide a consistent build environment with all the build-time dependencies, but the built executable should be able to run outside the container with no problem.

> I would like to build this project without docker

This project has a very strict dependency on the toolchain version (since LLVM does not have stable API), so doing the build outside container is going to get you into all sorts of configuration issues.

**Comment by Frityet** [comment]
> > because I am using MacOS
> 
> 
> 
> If you are using M1 or later, this project won't work on your system right now since it currently only supports x86-64. 
> 
> 
> 
> > I would like to test and help develop it outside of a container
> 
> 
> 
> The container is only to provide a consistent build environment with all the build-time dependencies, but the built executable should be able to run outside the container with no problem.
> 
> 
> 
> > I would like to build this project without docker
> 
> 
> 
> This project has a very strict dependency on the toolchain version (since LLVM does not have stable API), so doing the build outside container is going to get you into all sorts of configuration issues.

I have an x86_64 Mac, but the problem is that the generated binary is an elf for Linux, so I can't run it native. Could I also build LLVM with the project?

**Comment by sillycross** [comment]
In principle, it is possible to tweak CMake a bit to let it generate MacOS binary, but the problem here is, this project currently uses a corner Linux system call that is currently unavailable in x86-64 MacOS. This is something that I intend to eventually fix (see #8), but it's not trivial and there are higher priority things to do right now.

>  Could I also build LLVM with the project?

For now, maybe you have to workaround bu running the built executable in the container (you can easily write a script so running it is as simple as running a native executable). It's not suitable for performance testing, but should be enough if you just want to play with it a bit or make some changes. 

You definitely should not try to get rid of the build docker: it's there for very compelling reasons. Just to give you an example, Clang and LLVM are explicitly version-locked, which means you risk running into subtle weird bugs if you use LLVM-15 to process the IR generated by Clang-14 or Clang-16. So you need both LLVM-15 as the LLVM library AND Clang-15 as your C/C++ compiler to build LJR: you definitely don't want to do it on your host system, not to mention Clang/LLVM releases a new version every 6 months and we might follow up with their new releases at any time.

**Comment by hshq** [comment]
先说声抱歉，我就直接用中文不翻译了，因为我只能用翻译软件。反正你们要么能看懂，要么也能用软件翻译，我就直接上原汁原味的母语了。

一个月以前的事情，有些细节可能不确切了。

我没用过 docker ，C++ 和 python 也不会，有 C 和 Lua 经验。
我用一台 13年末的 mbp 和 m2 Mac mini 。考虑到这个项目适合的架构，先在 mbp(osx 11.7.10) 上尝试。docker 也装了，构建太慢了，好像有几百个测试用例吧，估计得几十个小时，而且还有错误，所以放弃了。主打性能的项目，看到这个用时，很难接受呀。

后来，根据那个用于构建的 python 文件，一边测试，一边根据反馈翻译成 macos 上的 shell 。期间当然遇到了很多问题，一一想办法快速解决，大概如下：

- 没有 memfd 模块：只有两处 memfd_create 调用，参数也比较单一，所以用内存盘和标准库的临时文件 API 模拟实现。
- runtime/vm.h 加上 #include <array> 。
- cmake 大量报错，加了很多 -Wno-XXX 这类选项。
- llvm 版本高了，用 homebrew 安装 v15 ；所以这方面不算难题。
- error: constexpr variable 'sorted_value' must be initialized by a constant expression

最后这个问题把我卡住了，这超出了我的能力，面对复杂项目中的这种 C++ 高端用法，我就放弃了。

**Comment by Frityet** [comment]
> In principle, it is possible to tweak CMake a bit to let it generate MacOS binary, but the problem here is, this project currently uses a corner Linux system call that is currently unavailable in x86-64 MacOS. This is something that I intend to eventually fix (see #8), but it's not trivial and there are higher priority things to do right now.
> 
> > Could I also build LLVM with the project?
> 
> For now, maybe you have to workaround bu running the built executable in the container (you can easily write a script so running it is as simple as running a native executable). It's not suitable for performance testing, but should be enough if you just want to play with it a bit or make some changes.
> 
> You definitely should not try to get rid of the build docker: it's there for very compelling reasons. Just to give you an example, Clang and LLVM are explicitly version-locked, which means you risk running into subtle weird bugs if you use LLVM-15 to process the IR generated by Clang-14 or Clang-16. So you need both LLVM-15 as the LLVM library AND Clang-15 as your C/C++ compiler to build LJR: you definitely don't want to do it on your host system, not to mention Clang/LLVM releases a new version every 6 months and we might follow up with their new releases at any time.

Got it, thank you!

**Comment by sillycross** [comment]
> 构建太慢了，好像有几百个测试用例吧，估计得几十个小时，而且还有错误，所以放弃了。主打性能的项目，看到这个用时，很难接受呀。

不至于这么慢的，在我的i7-12700H上面一次全新的build只要15分钟左右，就算用老i7-7700H也只要不到一个小时。你说还有错误，应该是某些环境配置出问题了。

>     * cmake 大量报错，加了很多 -Wno-XXX 这类选项。
>     * error: constexpr variable 'sorted_value' must be initialized by a constant expression
这个应该是你的Clang版本太低，或者有其他配置问题。有报错就说明配置有问题，不能无视蛮干的……

移植到Mac上真没那么简单，比如在build里有一步需要把Clang生成的Elf Object File重新parse成数据…… 你在Mac上搞，Clang就给你生成COFF Object了…… 这个除非你非常熟悉C/C++ cross compilation，或者非常能hack东西，否则真不是随便折腾折腾就能搞定的……
