### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by Frityet** [luajit-remake/luajit-remake#14]
One of the biggest downsides of both PUC-Rio Lua and LuaJIT is that both do not have any form of locking or mutexes within their states, making difficult to do real multi threading. Libraries that implement multi threading (see [lualanes](https://lualanes.github.io/lanes/) or [effil](https://github.com/effil/effil)) have many caveats, such as "userdata cannot be used unless specially prepared". Is there any plans/ideas for LJR to support this? From a more academic/research standpoint, what are the roadblocks that an interpreter/JIT have that makes multi-threading and synchronization difficult?

**Comment by sillycross** [comment]
The first thing you need to decide is your sharing model: share-everything (e.g., C threads), share-nothing (e.g., the examples you linked), and something in between are completely different design regimes.

So this is a language *design* question, not a language *implementation* question. When you want to design a new feature like this, the most important thing is to figure out what the application developers want, and only then you think about how you can implement it fast: if application developers don't like your design, it's useless no matter how fast it is.

It seems like you don't like the share-nothing model. And from a language *implementer*'s view, I can tell you that a share-everything model is going to be very very challenging to support efficiently. But again, as I said, the design should always be made based on the needs of application developers, not  language implementers: if application developers need share-everything, the job of language implementers is to make that happen. So to summarize, the question you asked is really orthogonal to this project. My job is to implement the language efficiently, which is orthogonal to the job of designing new features that fits the needs of application developers.

**Comment by UtoECat** [comment]
> From a more academic/research standpoint, what are the roadblocks that an interpreter/JIT have that makes multi-threading and synchronization difficult?

If we're talking about Lua, a programming language that tries to be as simple as possible (and somewhat safe), adding mutexes, thread-unsafe and thread-safe objects will create a ton of complexity for the Lua programmer, killing the whole idea of ​​the language.

Therefore, if it is necessary to implement multithreading, all objects(tables, functions, upvalues) must be thread safe. But synchronization is not free, and it is extremely difficult to remove all these synchronizations in the process of some kind of optimization. AND any sharing of objects between Lua threads/instances will require completely new approaches to garbage collection, memory allocation and optimisation in general... These are very difficult problems that are simply not worth solving.

And in cases where you REALLY need to have shared and syncronised data between states, it is better to write lua_CFunction getters/setters on an external associative array or choose one of theese fancy libraries for multithreading in Lua (also see how it's done in [love2d](https://github.com/love2d/love/blob/main/src/common/Variant.cpp), for example), instead of trying to increase the complexity of the Luavm to the JVM level :)

**Comment by Frityet** [comment]
> > From a more academic/research standpoint, what are the roadblocks that an interpreter/JIT have that makes multi-threading and synchronization difficult?
> 
> If we're talking about Lua, a programming language that tries to be as simple as possible (and somewhat safe), adding mutexes, thread-unsafe and thread-safe objects will create a ton of complexity for the Lua programmer, killing the whole idea of ​​the language.
> 
> Therefore, if it is necessary to implement multithreading, all objects(tables, functions, upvalues) must be thread safe. But synchronization is not free, and it is extremely difficult to remove all these synchronizations in the process of some kind of optimization. AND any sharing of objects between Lua threads/instances will require completely new approaches to garbage collection, memory allocation and optimisation in general... These are very difficult problems that are simply not worth solving.
> 
> And in cases where you REALLY need to have shared and syncronised data between states, it is better to write lua_CFunction getters/setters on an external associative array or choose one of theese fancy libraries for multithreading in Lua (also see how it's done in [love2d](https://github.com/love2d/love/blob/main/src/common/Variant.cpp), for example), instead of trying to increase the complexity of the Luavm to the JVM level :)

I see, thank you! I didn't know it was this difficult. I do hope that there is at least some bit of support though, as this is one of the lua features I really need for some projects I was working on

**Comment by sillycross** [comment]
@UtoECat Very nice explanation :)

> instead of trying to increase the complexity of the Luavm to the JVM level :)

It would be more than JVM level actually, at least in Java objects have a static shape and known field types :)
