### ISSUE TITLE
TString signedness

### ISSUE THREAD

**Issue by Frityet** [luajit-remake/luajit-remake#16]
Right now `TString::m_string` is defined as a `uint8_t *`. Is there any reason for this? Will some of the values be >127? I have been casting to a `char *` but this could be undefined

**Comment by sillycross** [comment]
> casting to a char * but this could be undefined

No, `reinterpret_cast` anything to `char*` is always well-defined. `char*` is specially exempt from strict aliasing rule (look at Type Aliasing section [on cppreference](https://en.cppreference.com/w/cpp/language/reinterpret_cast)).

> Will some of the values be >127?

It's a very weird question. A string is just a sequence of bytes and can have anything, like `\xff` gives you a value which byte representation is 0xff, and it's up to the user to interpret it as an unsigned 8-bit value (which is 255) or a signed 8-bit value (which is -1).

The "most C++" way would be to represent such an object as a `std::byte*`, but I guess hardly nobody use this in practice since it's not an arithmetic type. `uint8_t*` is used here because you can do more things with `uint8_t` (e.g., it would be undefined behavior to have a signed overflow or right-shifting a negative signed value).

**Comment by Frityet** [comment]
> No, reinterpret_cast anything to char* is always well-defined. char* is specially exempt from strict aliasing rule (look at Type Aliasing section on cppreference).
> 
> 

Ah this makes sense! Thank you, this answers my question. I was not aware of this
