### ISSUE TITLE
Bytecodes design

### ISSUE THREAD

**Issue by schungx** [luajit-remake/luajit-remake#2]
Hi, I am one of the current maintainers of [rhai](https://github.com/rhaiscript/rhai), a tree-walking interpreted language written in Rust.

While constantly debating whether to add a bytecodes VM, I came across this project.  I have been worrying about the fact that, even when compiling to bytecodes, it won't be of much benefit unless the types are traced.

I am wondering: I don't have a bytecodes system right now, but can design one.  Anything I need to know such that I can tailor-make this bytecodes for auto-VM generation using your tool?

I have no knowledge of Lua bytecodes, but I suppose most dynamic scripting languages are similar in that they work on hash objects/tables and need type tracing for best performance...

**Comment by sillycross** [comment]
Thanks for the question. 

> I have been worrying about the fact that, even when compiling to bytecodes, it won't be of much benefit unless the types are traced.

My experience is that even without type speculation (which is uncommon in interpreters anyway, though there are some works in this area, such as [Multi-Level Quickening](https://arxiv.org/abs/2109.02958) and Truffle's [Self-Optimizing AST Interpreter](http://lafo.ssw.uni-linz.ac.at/papers/2012_DLS_SelfOptimizingASTInterpreters.pdf)), the implementation of the interpreter itself can still make a big difference. This is, after all, why LuaJIT's hand-coded-in-assembly interpreter could get 2-3x the performance of PUC Lua.

Of course, the space of improvement highly depends on how good your existing interpreter is. But assuming that you are using a straightforward AST-walking interpreter (I don't know if it is the case or not), I believe there could be a lot of space of improvement. 

>  Anything I need to know such that I can tailor-make this bytecodes for auto-VM generation using your tool?

While I'm glad that Deegen might be used by something other than Lua, and I'm happy to answer questions you might have, I have to remind you that at this state it is a research project, so it comes with the usual caveats you would expect:
1. It currently only targets x86-64 Linux because I need to focus on the research novelties. 
2. It is currently written in C++, and heavily uses C++ magic to build the DSL and to "pass down" information to LLVM, as you already see. I don't know Rust so I don't know if it is possible (or how much work it would take) to rewrite it in Rust.
3. The interpreter generator (the "building the fastest Lua interpreter automatically" blog you saw) is not the most important part of this project. The important part is to automatically generate the JIT tiers, which I will be working on next. So at this moment I need to move on to the JIT generator next, and likely cannot spend time in adding more features to the interpreter generator to fit your need.

> I have no knowledge of Lua bytecodes
You can find the LuaJIT bytecode semantics [here](http://web.archive.org/web/20220607041223/http://wiki.luajit.org/Bytecode-2.0). LJR mostly reused the parser and the bytecode semantics, though we added more specializations to it for better performance.

**Comment by schungx** [comment]
> 3. The important part is to automatically generate the JIT tiers,

This I find extremely interesting.  I don't recall anything similar having been done ever before.  Parser generator, yes... but not an entire JIT layer generated semi-automatically...

In view of what you mentioned, I'll study a bit more of your code first.

And, yes, the interpreter which I use is a simple recursive tree-walker, with all the caveats attached to such an architecture.  It is quite heavily optimized (at least to me) in Rust, but still it runs roughly 3-5x slower than CPython on the Fibonacci benchmark (because it really taxes function calls and pushing frames).

I have once tried flatten the tree into bytecodes, but benchmarks didn't seem to show much speed difference to my surprise...  I conjecture that functions lookup might be dominating the runtime...

**Comment by sillycross** [comment]
> This I find extremely interesting. I don't recall anything similar having been done ever before. Parser generators, yes... but not an entire JIT layer generated semi-automatically...

You might be interested in reading my [Copy-and-Patch paper](https://fredrikbk.com/publications/copy-and-patch.pdf). Interpreter generator + copy-and-patch = baseline JIT (you just need to lower the Deegen-provided APIs a bit differently). 

> And, yes, the interpreter which I use is a simple recursive tree-walker, with all the caveats attached to such an architecture. It is quite heavily optimized (at least to me) in Rust, but still it runs roughly 3-5x slower than CPython on the Fibonacci benchmark (because it really taxes function calls and pushing frames).

Fibonacci benchmark imo is a very poor benchmark for testing interpreter performance. It stresses calls (which doesn't represent real-world workload), and more importantly, as a very minimal benchmark, its performance is highly dependent on how well your code layout makes the hardware branch predictor happy, which is something completely random. See [this](https://sillycross.github.io/2021/08/09/2021-08-09/) for more info.

> I have once tried flatten the tree into bytecodes, but benchmarks didn't seem to show much speed difference to my surprise... I conjecture that functions lookup might be dominating the runtime...

If you believe function lookup is the expensive part, you might want to employ *call inline caching*.

**Comment by schungx** [comment]
> If you believe function lookup is the expensive part, you might want to employ _call inline caching_.

I put in a function resolution cache that caches a function pointer based on a hashed value of the function name + parameter types.  It yielded a substantial performance boost.  I have been wondering whether a per-call-site cache would work better in this case...

**Comment by sillycross** [comment]
> I put in a function resolution cache that caches a function pointer based on a hashed value of the function name + parameter types. It yielded a substantial performance boost. I have been wondering whether a per-call-site cache would work better in this case...

Oh, I realized your "call" isn't taking a function object. It's more like, the "call" takes a string name (and the argument type list for overload resolution), and you need to resolve the call target at runtime.

In this case I think what you are doing is already almost optimal. If you haven't already, you can further keep a per-call-site "cached pointer" into your function resolution cache, so you can simply validate if that cached pointer is still valid at each call. This way, in most occasions, you can omit the hash lookup step that retrieves your target from the function resolution cache.

**Comment by schungx** [comment]
> In this case I think what you are doing is already almost optimal. If you haven't already, you can further keep a per-call-site "cached pointer" into your function resolution cache, so you can simply validate if that cached pointer is still valid at each call. This way, in most occasions, you can omit the hash lookup step that retrieves your target from the function resolution cache.

That's a great idea.  I'll try it out!  Thanks!

BTW, I timed Python 3 and compare again.  On the Fibonacci benchmark, it is roughly 4x slower.  But on a simple 1-million `while` loop, it is only about 2x slower.

**Comment by sillycross** [comment]
> BTW, I timed Python 3 and compare again. On the Fibonacci benchmark, it is roughly 4x slower. But on a simple 1-million `while` loop, it is only about 2x slower.

If you are slower than Python 3 it's likely you still have a lot of space of improvement :)

**Comment by schungx** [comment]
> If you are slower than Python 3 it's likely you still have a lot of space of improvement :)

Well, Python3 is a byte-codes interpreter... mine is just a recursive AST walker  ;-D

**Comment by tekknolagi** [comment]
> Well, Python3 is a byte-codes interpreter... mine is just a recursive AST walker ;-D

Method of interpretation aside, there are a lot of things that can dramatically change the performance of a runtime, including:

* allocation
* slow attribute/method lookups
* slow calls
* moving data around for no reason (between formats, etc)
* checking types and invariants repeatedly

Even if you directly ported to a bytecode interpreter, there are other places left to optimize, and it might not be obvious what the performance culprits were if you looked at your program under a profiler.
